name: carrotquest_sdk
description: Conversational platform for business. Flutter sdk.
version: 0.0.4

repository: https://github.com/carrotquest/flutter-sdk  
homepage: https://www.carrotquest.io/

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: io.carrotquest.carrotquest_sdk
        pluginClass: CarrotquestSdkPlugin
      ios:
        pluginClass: CarrotquestSdkPlugin
